In [351]:
import pandas as pd
import os

In [380]:
포맷파일디렉토리="C:/Users/chlee/Desktop/crime-forecast-hanium/포맷안된파일"
파일이름="범죄발생 지역(1964-2013).xlsx"

데이터프레임=pd.read_excel(os.path.join(포맷파일디렉토리,파일이름),encoding='utf-8')
데이터프레임=데이터프레임.drop(' 범죄명칭.2',axis=1) #1열방향
데이터프레임=데이터프레임.T.drop(0,axis=1)
데이터프레임

,1,2,3,4,5,6,7,8,9,10,...,252,253,254,255,256,257,258,259,260,261
범죄명칭,범죄명칭,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,경제범죄,경제범죄,경제범죄,경제범죄,...,환경범죄,환경범죄,환경범죄,환경범죄,환경범죄,환경범죄,환경범죄,환경범죄,환경범죄,환경범죄
범죄명칭,범죄명칭,강도,기타_강력범죄,방화,방화,살인,금융범죄,금융범죄,금융범죄,금융범죄,...,대기,동,물,물,물,산림,토양,해양,해양,해양
범죄명칭.1,범죄명칭,강도,총포.도검.화약류등단속법,방화,실화,살인,대부업등의등록및금융이용자보호에관한법,대외무역법,부정수표단속법,상호신용금고법,...,대기환경보전법,식물,수질환경보전법,지하수법,하천법,산림자원의조성및관리에관한법률위반,폐기물관리법,수산자원관리법,수산자원보호령,해양오염방지법
2013,서울,433,32,331,284,159,530,116,1935,,...,86,,0,2,0,7,22,3,0,0
2013.1,부산,224,21,112,227,78,399,25,491,,...,97,0,0,0,4,13,819,130,0,1
2013.2,대구,110,6,76,59,41,179,6,303,,...,42,0,0,2,7,8,29,9,0,0
2013.3,인천,117,14,100,68,39,64,26,290,,...,103,0,0,0,1,20,38,96,0,0
2013.4,광주,86,2,45,134,23,65,1,96,,...,5,0,0,0,0,2,11,0,0,0
2013.5,대전,70,2,64,83,30,51,1,85,,...,18,0,0,0,1,4,12,0,0,0
2013.6,울산,45,33,37,51,18,57,2,18,,...,47,0,0,1,16,5,21,26,0,0
2013.7,부천,36,2,25,12,15,39,2,65,,...,10,0,0,0,0,2,6,0,0,0
2013.8,수원,40,3,40,89,15,30,3,89,,...,4,0,0,0,0,0,8,0,0,0
2013.9,성남,33,3,37,14,7,49,2,52,,...,2,0,0,0,0,3,2,0,0,0
2013.10,전주,13,1,19,16,14,14,0,19,,...,0,0,0,0,3,6,5,0,0,0
2013.11,안양,9,1,13,10,8,8,1,43,,...,3,0,0,0,1,0,3,0,0,0
2013.12,청주,34,7,11,39,13,22,1,23,,...,3,0,0,1,1,2,2,0,0,0
2013.13,마산,,,,,,,,,,...,,0,,,,,,,,
2013.14,창원,49,2,39,33,24,89,2,72,,...,34,,0,0,2,8,12,353,1,0
2013.15,광명,5,1,6,22,2,6,1,24,,...,1,0,0,0,0,0,2,0,0,0
2013.16,포항,9,4,21,20,8,14,2,26,,...,36,0,0,0,0,12,17,1010,0,0
2013.17,안산,35,3,27,30,16,15,3,22,,...,49,0,0,0,0,9,35,4,0,0
2013.18,진주,12,2,12,5,7,18,2,9,,...,13,0,0,0,1,1,4,0,0,0
2013.19,고양,23,4,27,23,12,97,1,77,,...,13,0,0,0,5,10,16,1,0,0
2013.20,제주,38,11,46,58,30,22,1,90,,...,3,0,0,0,2,8,12,61,0,0
2013.21,목포,19,0,9,9,5,26,2,23,,...,2,0,0,0,0,0,2,18,0,0
2013.22,의정부,13,1,15,17,6,10,0,28,,...,2,0,0,0,1,0,1,0,0,0
2013.23,익산,17,6,8,13,3,10,0,13,,...,5,0,0,2,0,3,5,0,0,0
2013.24,군산,11,1,11,12,7,5,2,8,,...,9,0,0,1,0,10,5,99,0,0
2013.25,구미,18,2,11,14,7,8,0,26,,...,22,0,0,0,1,6,12,0,0,0
2013.26,천안,39,3,43,31,20,29,0,38,,...,12,0,0,0,0,8,14,0,0,0
2013.27,여수,6,1,19,20,9,11,1,37,,...,6,0,0,0,0,1,427,1837,0,0
2013.28,춘천,7,0,8,11,6,4,0,27,,...,11,0,0,0,4,18,5,0,0,0
2013.29,원주,11,5,13,12,11,47,0,20,,...,4,0,0,0,1,8,9,0,0,0
2013.30,평택,16,6,20,39,9,33,5,11,,...,40,0,0,0,0,17,25,0,0,0
2013.31,경주,11,1,21,13,6,11,0,0,,...,4,0,0,0,1,9,8,10,0,0
2013.32,김해,15,3,14,7,10,12,2,32,,...,98,0,0,0,4,5,42,0,0,0
2013.33,순천,15,2,8,16,2,6,0,24,,...,11,0,0,0,1,4,4,3,0,0
2013.34,군포,8,0,9,6,0,6,0,77,,...,5,0,0,0,0,0,1,0,0,0
2013.35,남양주,10,4,9,19,7,14,0,54,,...,17,0,0,0,6,1,42,0,0,0
2013.36,강릉,7,3,10,11,6,10,0,56,,...,5,0,0,2,1,9,11,48,0,0
2013.37,충주,7,0,9,17,6,8,0,0,,...,4,0,0,0,1,4,17,0,0,0
2013.38,안동,8,4,6,5,4,1,1,2,,...,3,0,0,0,1,17,2,1,0,0
2013.39,경산,7,1,26,7,2,9,0,4,,...,6,0,0,0,1,5,9,8,0,0
2013.40,아산,18,2,9,14,6,5,1,9,,...,14,0,0,0,0,10,5,2,0,0
2013.41,거제,4,0,6,10,3,5,0,3,,...,6,0,0,2,0,6,4,52,0,0
2013.42,김천,4,2,4,13,2,2,0,1,,...,4,0,0,0,0,6,5,1,0,0
2013.43,정읍,3,4,5,18,2,5,0,4,,...,0,0,0,0,1,5,7,0,0,0
2013.44,용인,18,2,21,89,15,17,4,85,,...,18,0,0,0,0,11,18,0,0,0
2013.45,시흥,26,1,10,10,9,9,2,46,,...,21,0,0,0,0,0,33,0,0,0
2013.46,파주,13,1,13,17,6,28,0,78,,...,47,0,0,0,4,8,22,0,0,0
2013.47,양산,5,0,4,10,2,5,3,4,,...,15,0,0,0,0,1,6,0,0,0
2013.48,이천,3,1,5,9,7,6,0,6,,...,29,0,0,0,0,12,9,0,0,0
2013.49,구리,5,1,4,7,1,12,0,33,,...,6,0,0,0,1,0,8,0,0,0
2013.50,서산,2,2,9,2,5,3,0,0,,...,7,0,0,0,0,4,3,2,0,0
2013.51,제천,3,0,4,9,2,1,0,1,,...,1,0,0,0,0,5,8,0,0,0
2013.52,논산,3,1,5,6,10,2,0,11,,...,13,0,0,0,0,4,10,0,0,0
2013.53,기타도시,141,29,162,205,95,178,24,605,,...,711,0,0,2,21,154,352,287,0,0
2013.54,도시이외,99,56,126,291,116,128,17,174,,...,244,0,0,7,64,237,225,890,0,0
Unnamed: 59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
Unnamed: 60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [353]:
콜론=[]
for i in 데이터프레임.columns :
    이름=""
    for name in ['범죄명칭',' 범죄명칭',' 범죄명칭.1'] :
        이름 += 데이터프레임.ix[name][i] +'/'
    콜론.append(이름)

데이터프레임.columns = 콜론
데이터프레임=데이터프레임.reset_index(drop=True)

In [354]:
데이터프레임=데이터프레임.drop([0,1,2])

In [355]:
데이터프레임.columns = 데이터프레임.columns[1:].insert(0,'도시')
데이터프레임=데이터프레임.reset_index(drop=True)
데이터프레임

,도시,강력범죄/ 강도/ 강도/,강력범죄/ 기타_강력범죄/ 총포.도검.화약류등단속법/,강력범죄/ 방화/ 방화/,강력범죄/ 방화/ 실화/,강력범죄/ 살인/ 살인/,경제범죄/ 금융범죄/ 대부업등의등록및금융이용자보호에관한법/,경제범죄/ 금융범죄/ 대외무역법/,경제범죄/ 금융범죄/ 부정수표단속법/,경제범죄/ 금융범죄/ 상호신용금고법/,...,환경범죄/ 대기/ 대기환경보전법/,환경범죄/ 동/식물/,환경범죄/ 물/ 수질환경보전법/,환경범죄/ 물/ 지하수법/,환경범죄/ 물/ 하천법/,환경범죄/ 산림/ 산림자원의조성및관리에관한법률위반/,환경범죄/ 토양/ 폐기물관리법/,환경범죄/ 해양/ 수산자원관리법/,환경범죄/ 해양/ 수산자원보호령/,환경범죄/ 해양/ 해양오염방지법/
0,서울,433,32,331,284,159,530,116,1935,,...,86,,0,2,0,7,22,3,0,0
1,부산,224,21,112,227,78,399,25,491,,...,97,0,0,0,4,13,819,130,0,1
2,대구,110,6,76,59,41,179,6,303,,...,42,0,0,2,7,8,29,9,0,0
3,인천,117,14,100,68,39,64,26,290,,...,103,0,0,0,1,20,38,96,0,0
4,광주,86,2,45,134,23,65,1,96,,...,5,0,0,0,0,2,11,0,0,0
5,대전,70,2,64,83,30,51,1,85,,...,18,0,0,0,1,4,12,0,0,0
6,울산,45,33,37,51,18,57,2,18,,...,47,0,0,1,16,5,21,26,0,0
7,부천,36,2,25,12,15,39,2,65,,...,10,0,0,0,0,2,6,0,0,0
8,수원,40,3,40,89,15,30,3,89,,...,4,0,0,0,0,0,8,0,0,0
9,성남,33,3,37,14,7,49,2,52,,...,2,0,0,0,0,3,2,0,0,0
10,전주,13,1,19,16,14,14,0,19,,...,0,0,0,0,3,6,5,0,0,0
11,안양,9,1,13,10,8,8,1,43,,...,3,0,0,0,1,0,3,0,0,0
12,청주,34,7,11,39,13,22,1,23,,...,3,0,0,1,1,2,2,0,0,0
13,마산,,,,,,,,,,...,,0,,,,,,,,
14,창원,49,2,39,33,24,89,2,72,,...,34,,0,0,2,8,12,353,1,0
15,광명,5,1,6,22,2,6,1,24,,...,1,0,0,0,0,0,2,0,0,0
16,포항,9,4,21,20,8,14,2,26,,...,36,0,0,0,0,12,17,1010,0,0
17,안산,35,3,27,30,16,15,3,22,,...,49,0,0,0,0,9,35,4,0,0
18,진주,12,2,12,5,7,18,2,9,,...,13,0,0,0,1,1,4,0,0,0
19,고양,23,4,27,23,12,97,1,77,,...,13,0,0,0,5,10,16,1,0,0
20,제주,38,11,46,58,30,22,1,90,,...,3,0,0,0,2,8,12,61,0,0
21,목포,19,0,9,9,5,26,2,23,,...,2,0,0,0,0,0,2,18,0,0
22,의정부,13,1,15,17,6,10,0,28,,...,2,0,0,0,1,0,1,0,0,0
23,익산,17,6,8,13,3,10,0,13,,...,5,0,0,2,0,3,5,0,0,0
24,군산,11,1,11,12,7,5,2,8,,...,9,0,0,1,0,10,5,99,0,0
25,구미,18,2,11,14,7,8,0,26,,...,22,0,0,0,1,6,12,0,0,0
26,천안,39,3,43,31,20,29,0,38,,...,12,0,0,0,0,8,14,0,0,0
27,여수,6,1,19,20,9,11,1,37,,...,6,0,0,0,0,1,427,1837,0,0
28,춘천,7,0,8,11,6,4,0,27,,...,11,0,0,0,4,18,5,0,0,0
29,원주,11,5,13,12,11,47,0,20,,...,4,0,0,0,1,8,9,0,0,0
30,평택,16,6,20,39,9,33,5,11,,...,40,0,0,0,0,17,25,0,0,0
31,경주,11,1,21,13,6,11,0,0,,...,4,0,0,0,1,9,8,10,0,0
32,김해,15,3,14,7,10,12,2,32,,...,98,0,0,0,4,5,42,0,0,0
33,순천,15,2,8,16,2,6,0,24,,...,11,0,0,0,1,4,4,3,0,0
34,군포,8,0,9,6,0,6,0,77,,...,5,0,0,0,0,0,1,0,0,0
35,남양주,10,4,9,19,7,14,0,54,,...,17,0,0,0,6,1,42,0,0,0
36,강릉,7,3,10,11,6,10,0,56,,...,5,0,0,2,1,9,11,48,0,0
37,충주,7,0,9,17,6,8,0,0,,...,4,0,0,0,1,4,17,0,0,0
38,안동,8,4,6,5,4,1,1,2,,...,3,0,0,0,1,17,2,1,0,0
39,경산,7,1,26,7,2,9,0,4,,...,6,0,0,0,1,5,9,8,0,0
40,아산,18,2,9,14,6,5,1,9,,...,14,0,0,0,0,10,5,2,0,0
41,거제,4,0,6,10,3,5,0,3,,...,6,0,0,2,0,6,4,52,0,0
42,김천,4,2,4,13,2,2,0,1,,...,4,0,0,0,0,6,5,1,0,0
43,정읍,3,4,5,18,2,5,0,4,,...,0,0,0,0,1,5,7,0,0,0
44,용인,18,2,21,89,15,17,4,85,,...,18,0,0,0,0,11,18,0,0,0
45,시흥,26,1,10,10,9,9,2,46,,...,21,0,0,0,0,0,33,0,0,0
46,파주,13,1,13,17,6,28,0,78,,...,47,0,0,0,4,8,22,0,0,0
47,양산,5,0,4,10,2,5,3,4,,...,15,0,0,0,0,1,6,0,0,0
48,이천,3,1,5,9,7,6,0,6,,...,29,0,0,0,0,12,9,0,0,0
49,구리,5,1,4,7,1,12,0,33,,...,6,0,0,0,1,0,8,0,0,0
50,서산,2,2,9,2,5,3,0,0,,...,7,0,0,0,0,4,3,2,0,0
51,제천,3,0,4,9,2,1,0,1,,...,1,0,0,0,0,5,8,0,0,0
52,논산,3,1,5,6,10,2,0,11,,...,13,0,0,0,0,4,10,0,0,0
53,기타도시,141,29,162,205,95,178,24,605,,...,711,0,0,2,21,154,352,287,0,0
54,도시이외,99,56,126,291,116,128,17,174,,...,244,0,0,7,64,237,225,890,0,0
55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [372]:
데이터프레임=데이터프레임.dropna()

In [373]:
new데이터프레임=데이터프레임

In [374]:
인덱스 = new데이터프레임['도시'].values
new데이터프레임=new데이터프레임.drop('도시',axis=1)

In [375]:
new데이터프레임=new데이터프레임.set_index(인덱스,drop=True)

In [377]:
new데이터프레임

,강력범죄/ 강도/ 강도/,강력범죄/ 기타_강력범죄/ 총포.도검.화약류등단속법/,강력범죄/ 방화/ 방화/,강력범죄/ 방화/ 실화/,강력범죄/ 살인/ 살인/,경제범죄/ 금융범죄/ 대부업등의등록및금융이용자보호에관한법/,경제범죄/ 금융범죄/ 대외무역법/,경제범죄/ 금융범죄/ 부정수표단속법/,경제범죄/ 금융범죄/ 상호신용금고법/,경제범죄/ 금융범죄/ 신용정보의이용및보호에관한법률/,...,환경범죄/ 대기/ 대기환경보전법/,환경범죄/ 동/식물/,환경범죄/ 물/ 수질환경보전법/,환경범죄/ 물/ 지하수법/,환경범죄/ 물/ 하천법/,환경범죄/ 산림/ 산림자원의조성및관리에관한법률위반/,환경범죄/ 토양/ 폐기물관리법/,환경범죄/ 해양/ 수산자원관리법/,환경범죄/ 해양/ 수산자원보호령/,환경범죄/ 해양/ 해양오염방지법/
서울,433,32,331,284,159,530,116,1935,,30,...,86,,0,2,0,7,22,3,0,0
부산,224,21,112,227,78,399,25,491,,17,...,97,0,0,0,4,13,819,130,0,1
대구,110,6,76,59,41,179,6,303,,4,...,42,0,0,2,7,8,29,9,0,0
인천,117,14,100,68,39,64,26,290,,6,...,103,0,0,0,1,20,38,96,0,0
광주,86,2,45,134,23,65,1,96,,4,...,5,0,0,0,0,2,11,0,0,0
대전,70,2,64,83,30,51,1,85,,1,...,18,0,0,0,1,4,12,0,0,0
울산,45,33,37,51,18,57,2,18,,6,...,47,0,0,1,16,5,21,26,0,0
부천,36,2,25,12,15,39,2,65,,3,...,10,0,0,0,0,2,6,0,0,0
수원,40,3,40,89,15,30,3,89,,0,...,4,0,0,0,0,0,8,0,0,0
성남,33,3,37,14,7,49,2,52,,1,...,2,0,0,0,0,3,2,0,0,0
전주,13,1,19,16,14,14,0,19,,0,...,0,0,0,0,3,6,5,0,0,0
안양,9,1,13,10,8,8,1,43,,0,...,3,0,0,0,1,0,3,0,0,0
청주,34,7,11,39,13,22,1,23,,0,...,3,0,0,1,1,2,2,0,0,0
마산,,,,,,,,,,,...,,0,,,,,,,,
창원,49,2,39,33,24,89,2,72,,2,...,34,,0,0,2,8,12,353,1,0
광명,5,1,6,22,2,6,1,24,,2,...,1,0,0,0,0,0,2,0,0,0
포항,9,4,21,20,8,14,2,26,,38,...,36,0,0,0,0,12,17,1010,0,0
안산,35,3,27,30,16,15,3,22,,0,...,49,0,0,0,0,9,35,4,0,0
진주,12,2,12,5,7,18,2,9,,0,...,13,0,0,0,1,1,4,0,0,0
고양,23,4,27,23,12,97,1,77,,19,...,13,0,0,0,5,10,16,1,0,0
제주,38,11,46,58,30,22,1,90,,2,...,3,0,0,0,2,8,12,61,0,0
목포,19,0,9,9,5,26,2,23,,0,...,2,0,0,0,0,0,2,18,0,0
의정부,13,1,15,17,6,10,0,28,,1,...,2,0,0,0,1,0,1,0,0,0
익산,17,6,8,13,3,10,0,13,,1,...,5,0,0,2,0,3,5,0,0,0
군산,11,1,11,12,7,5,2,8,,1,...,9,0,0,1,0,10,5,99,0,0
구미,18,2,11,14,7,8,0,26,,0,...,22,0,0,0,1,6,12,0,0,0
천안,39,3,43,31,20,29,0,38,,0,...,12,0,0,0,0,8,14,0,0,0
여수,6,1,19,20,9,11,1,37,,0,...,6,0,0,0,0,1,427,1837,0,0
춘천,7,0,8,11,6,4,0,27,,0,...,11,0,0,0,4,18,5,0,0,0
원주,11,5,13,12,11,47,0,20,,0,...,4,0,0,0,1,8,9,0,0,0
평택,16,6,20,39,9,33,5,11,,0,...,40,0,0,0,0,17,25,0,0,0
경주,11,1,21,13,6,11,0,0,,8,...,4,0,0,0,1,9,8,10,0,0
김해,15,3,14,7,10,12,2,32,,3,...,98,0,0,0,4,5,42,0,0,0
순천,15,2,8,16,2,6,0,24,,0,...,11,0,0,0,1,4,4,3,0,0
군포,8,0,9,6,0,6,0,77,,1,...,5,0,0,0,0,0,1,0,0,0
남양주,10,4,9,19,7,14,0,54,,0,...,17,0,0,0,6,1,42,0,0,0
강릉,7,3,10,11,6,10,0,56,,0,...,5,0,0,2,1,9,11,48,0,0
충주,7,0,9,17,6,8,0,0,,0,...,4,0,0,0,1,4,17,0,0,0
안동,8,4,6,5,4,1,1,2,,0,...,3,0,0,0,1,17,2,1,0,0
경산,7,1,26,7,2,9,0,4,,0,...,6,0,0,0,1,5,9,8,0,0
아산,18,2,9,14,6,5,1,9,,0,...,14,0,0,0,0,10,5,2,0,0
거제,4,0,6,10,3,5,0,3,,0,...,6,0,0,2,0,6,4,52,0,0
김천,4,2,4,13,2,2,0,1,,0,...,4,0,0,0,0,6,5,1,0,0
정읍,3,4,5,18,2,5,0,4,,0,...,0,0,0,0,1,5,7,0,0,0
용인,18,2,21,89,15,17,4,85,,0,...,18,0,0,0,0,11,18,0,0,0
시흥,26,1,10,10,9,9,2,46,,0,...,21,0,0,0,0,0,33,0,0,0
파주,13,1,13,17,6,28,0,78,,0,...,47,0,0,0,4,8,22,0,0,0
양산,5,0,4,10,2,5,3,4,,0,...,15,0,0,0,0,1,6,0,0,0
이천,3,1,5,9,7,6,0,6,,0,...,29,0,0,0,0,12,9,0,0,0
구리,5,1,4,7,1,12,0,33,,0,...,6,0,0,0,1,0,8,0,0,0
서산,2,2,9,2,5,3,0,0,,0,...,7,0,0,0,0,4,3,2,0,0
제천,3,0,4,9,2,1,0,1,,0,...,1,0,0,0,0,5,8,0,0,0
논산,3,1,5,6,10,2,0,11,,0,...,13,0,0,0,0,4,10,0,0,0
기타도시,141,29,162,205,95,178,24,605,,0,...,711,0,0,2,21,154,352,287,0,0
도시이외,99,56,126,291,116,128,17,174,,7,...,244,0,0,7,64,237,225,890,0,0

In [378]:
포맷파일디렉토리="C:/Users\chlee/Desktop/crime-forecast-hanium/데이터파일"
파일이름="범죄발생 지역(1964-2013).xlsx"
new데이터프레임.to_excel(os.path.join(포맷파일디렉토리,파일이름))